# Generated by Django 4.0.3 on 2022-03-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_orders_total_orders_user_alter_orders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
