# Generated by Django 4.0.3 on 2022-03-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_products_quantity_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
